export const GLOBAL_LOADDING = 'GLOBAL_LOADDING'
export const GLOBAL_PROGRESS = 'GLOBAL_PROGRESS'
export const GLOBAL_SHOWMSG = 'GLOBAL_SHOWMSG'
export const GLOBAL_HIDEMSG = 'GLOBAL_HIDEMSG'

export const RECEIVE_TOPICS = 'RECEIVE_TOPICS'
export const RECEIVE_ARTICLE = 'RECEIVE_ARTICLE'
export const RECEIVE_COMMENT = 'RECEIVE_COMMENT'
export const POST_COMMENT = 'POST_COMMENT'

export const RECEIVE_ADMIN_TOPICS = 'RECEIVE_ADMIN_TOPICS'
export const RECEIVE_ADMIN_ARTICLE = 'RECEIVE_ADMIN_ARTICLE'

export const UPDATE_ADMIN_ARTICLE = 'UPDATE_ADMIN_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const RECOVER_ARTICLE = 'RECOVER_ARTICLE'
